---
services:
  web:
    build: ./
    image: rentacar:v1
    container_name: web
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ".:/app"
    command: sh docker-entrypoint.sh
    environment:
      - NODE_ENV="production"
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    restart: unless-stopped

  db:
    # amd64
    image: mysql:5.7
    # arm64
    # image: mariadb:latest
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./db/db.sql:/docker-entrypoint-initdb.d/db.sql"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped

volumes:
  node_modules:
